import {CLI_ARTIFACT_TYPES} from '../artifactTypeIds';
import type {CliCapabilityProfile} from './types';

/** Current `--experimental` SQLRooms CLI behavior. */
export const EXPERIMENTAL_CLI_CAPABILITY_PROFILE = {
  name: 'experimental',
  version: 1,
  artifacts: {
    creatable: CLI_ARTIFACT_TYPES,
    runContext: CLI_ARTIFACT_TYPES,
  },
  blocks: {
    stateful: [
      'dashboard',
      'pivot',
      'data-table',
      'map',
      'document',
      'sql-query',
      'html-app',
      'python',
    ],
    aiContext: ['chart', 'dashboard', 'html-app', 'map'],
    interactiveRenderers: [
      'chart',
      'dashboard',
      'pivot',
      'data-table',
      'map',
      'document',
      'sql-query',
      'html-app',
      'python',
    ],
    placeholderRenderers: [],
  },
  commands: [
    'dashboard',
    'mosaic-dashboard',
    'document',
    'block-document',
    'cli-block-document',
    'block-document-python',
    'html-app-revision',
  ],
  ai: {
    instructionSets: ['stable', 'experimental'],
    topLevelToolGroups: [
      'default-data-analysis',
      'artifact-context',
      'dashboard-agent',
      'html-app-agent',
      'worksheet-agent',
      'webcontainer',
      'chart',
      'chart-image-for-markdown',
    ],
    nestedAgents: ['dashboard', 'worksheet', 'worksheet-dashboard', 'html-app'],
  },
  skills: [],
  lifecycleSlices: [
    'ai',
    'ai-settings',
    'app-project',
    'artifacts',
    'artifact-ai',
    'block-documents',
    'canvas',
    'cells',
    'crdt',
    'dashboard',
    'dashboard-features',
    'db-settings',
    'deck-maps',
    'documents',
    'html-apps',
    'mosaic',
    'notebook',
    'pivot',
    'python',
    'room-shell',
    'sql-editor',
    'webcontainer',
    'workspace-ui',
  ],
  dashboard: {deckMaps: true},
} as const satisfies CliCapabilityProfile;
