packages:
  - 'packages/*'
  - 'examples/*'
  - '!packages/kepler.gl'
  - 'packages/kepler.gl/src/*'
  - 'apps/*'
  - 'python/*'
allowBuilds:
  '@mongodb-js/zstd': false
  '@swc/core': true
  '@vaadin/vaadin-usage-statistics': false
  esbuild: true
  node-liblzma: true
  sharp: false
  unrs-resolver: true
