import {Tool} from 'ai';
import {DatabaseAiAdapter} from '../../ai/database-types';
import {ToolOutput} from '../../ai/tool-types';

export type ChartToolOutput<T> = ToolOutput<{
  details: string;
  data: T;
}>;

/**
 * Arguments passed to chart panel creation and update callbacks.
 */
type AddChartFunctionArgs = {
  /** Optional table name; worksheet charts require it, dashboard charts may inherit it. */
  tableName?: string; // Optional: worksheet charts need it, dashboard charts inherit from dashboard.selectedTable
  /** Optional existing dashboard panel ID to update instead of creating a new panel. */
  panelId?: string;
  /** Optional human-readable chart title. */
  title?: string;
  /** Chart configuration generated by the chart tool. */
  config: any;
};

/**
 * Callback used by chart tools to add or update a rendered chart panel.
 */
export type AddChartFunction = (
  args: AddChartFunctionArgs,
) => string | Promise<string>;

/**
 * Dependencies for chart configuration tools.
 * Simple and minimal.
 */
export type ChartToolParams = {
  /** Add chart to dashboard */
  addChart: AddChartFunction;
  /** Maximum data points for non-aggregated charts */
  maxDataPoints: number;
  /** Database adapter for resolving tables and columns. */
  databaseAdapter: DatabaseAiAdapter;
};

/**
 * Factory for creating chart configuration tools.
 * Chart tools generate ChartConfig and use resolveTable for validation.
 */
export type ChartToolFactory<TInput, TOutput> = (
  params: ChartToolParams,
) => Tool<TInput, ChartToolOutput<TOutput>>;
