import {sanitizeQuery, useSql} from '@sqlrooms/duckdb';
import {PaginationState, SortingState} from '@tanstack/table-core';
import {FC, useMemo, useState} from 'react';
import DataTablePaginated, {
  DataTablePaginatedProps,
} from './DataTablePaginated';
import {QueryDataTableActionsMenu} from './QueryDataTableActionsMenu';
import useArrowDataTable, {
  ArrowDataTableValueFormatter,
} from './useArrowDataTable';
import {makePagedQuery} from './utils';

export type QueryDataTableProps = {
  className?: string;
  /** Custom font size for the table e.g. text-xs, text-sm, text-md, text-lg, text-base */
  fontSize?: DataTablePaginatedProps<any>['fontSize'];
  query: string;
  queryKeyComponents?: unknown[];
  renderActions?: (query: string) => React.ReactNode;
  /** Custom value formatter for arrow data */
  formatValue?: ArrowDataTableValueFormatter;
};

const QueryDataTable: FC<QueryDataTableProps> = ({
  className,
  fontSize = 'text-xs',
  query,
  renderActions = (query) => <QueryDataTableActionsMenu query={query} />,
  formatValue,
}) => {
  const [sorting, setSorting] = useState<SortingState>([]);
  const [pagination, setPagination] = useState<PaginationState>({
    pageIndex: 0,
    pageSize: 100,
  });

  // Sanitize the query generated by LLM to remove trailing semicolons, comments, and extra spaces
  const sanitizedQuery = useMemo(() => sanitizeQuery(query), [query]);
  const pagedQuery = makePagedQuery(sanitizedQuery, sorting, pagination);
  const queryResult = useSql({query: pagedQuery});
  const countQueryResult = useSql<{count: number}>({
    query: `SELECT COUNT(*)::int AS count FROM (${sanitizedQuery})`,
  });
  const arrowTableData = useArrowDataTable(queryResult.data?.arrowTable, {
    formatValue,
  });

  if (queryResult.error) {
    return (
      <div className="h-full w-full overflow-auto p-5">
        <pre className="text-xs leading-tight text-red-500">
          {queryResult.error?.message ?? 'Unknown error'}
        </pre>
      </div>
    );
  }

  const numRows = countQueryResult.data
    ? (countQueryResult.data.toArray()[0]?.count ?? 0)
    : undefined;

  return (
    <DataTablePaginated
      {...arrowTableData}
      enableRowSelection={true}
      className={className}
      fontSize={fontSize}
      numRows={numRows}
      isFetching={queryResult.isLoading}
      pagination={pagination}
      onPaginationChange={setPagination}
      sorting={sorting}
      onSortingChange={setSorting}
      footerActions={renderActions ? renderActions(sanitizedQuery) : null}
    />
  );
};

export default QueryDataTable;
