import type * as Monaco from 'monaco-editor';

/**
 * DuckDB SQL language constants for Monaco Editor
 */

export const DUCKDB_KEYWORDS = [
  // Standard SQL keywords
  'SELECT',
  'FROM',
  'WHERE',
  'GROUP',
  'BY',
  'HAVING',
  'ORDER',
  'LIMIT',
  'OFFSET',
  'INSERT',
  'INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE',
  'CREATE',
  'ALTER',
  'DROP',
  'TABLE',
  'VIEW',
  'INDEX',
  'TRIGGER',
  'PROCEDURE',
  'FUNCTION',
  'DATABASE',
  'SCHEMA',
  'JOIN',
  'INNER',
  'LEFT',
  'RIGHT',
  'FULL',
  'OUTER',
  'CROSS',
  'NATURAL',
  'ON',
  'USING',
  'AND',
  'OR',
  'NOT',
  'NULL',
  'IS',
  'IN',
  'BETWEEN',
  'LIKE',
  'AS',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'DISTINCT',
  'ALL',
  'UNION',
  'INTERSECT',
  'EXCEPT',
  'WITH',
  'CAST',
  'PRIMARY',
  'KEY',
  'FOREIGN',
  'REFERENCES',
  'CONSTRAINT',
  'DEFAULT',
  'CHECK',
  'UNIQUE',
  'INDEX',
  'CASCADE',
  'RESTRICT',
  'ASC',
  'DESC',
  'IF',
  'EXISTS',
  'TRUE',
  'FALSE',
  // DuckDB specific keywords
  'PRAGMA',
  'RETURNING',
  'QUALIFY',
  'PIVOT',
  'UNPIVOT',
  'EXCLUDE',
  'INCLUDE',
  'WINDOW',
  'FILTER',
  'WITHIN',
  'OVER',
  'PARTITION',
  'RANGE',
  'ROWS',
  'GROUPS',
  'PRECEDING',
  'FOLLOWING',
  'CURRENT',
  'ROW',
  'TIES',
  'OTHERS',
  'EXCLUDE',
  'RESPECT',
  'NULLS',
  'FIRST',
  'LAST',
  'MATERIALIZED',
  'RECURSIVE',
  'TEMPORARY',
  'TEMP',
  'UNLOGGED',
  'GLOBAL',
  'LOCAL',
  'STORED',
  'VIRTUAL',
  'DELIMITED',
  'CSV',
  'JSON',
  'COPY',
  'DESCRIBE',
  'EXPLAIN',
  'SUMMARIZE',
  'PROFILE',
  'LOAD',
  'INSTALL',
  'FORCE',
  'PARALLEL',
  'SEQUENTIAL',
  'PRAGMA',
];
// DuckDB functions
export const DUCKDB_FUNCTIONS = [
  // ... getFunctionSuggestions
];

// SQL operators
export const SQL_OPERATORS = [
  '+',
  '-',
  '*',
  '/',
  '%',
  '&',
  '|',
  '^',
  '=',
  '<>',
  '!=',
  '>',
  '>=',
  '<',
  '<=',
  '<<',
  '>>',
  '||',
  '::',
  '->>',
  '->',
  '~',
  '!',
  '@',
];

// SQL variables
export const SQL_VARIABLES = [
  '$1',
  '$2',
  '$3',
  '$4',
  '$5',
  '$6',
  '$7',
  '$8',
  '$9',
];

// SQL pseudo columns
export const SQL_PSEUDO_COLUMNS = [
  '$ACTION',
  '$IDENTITY',
  '$ROWGUID',
  '$PARTITION',
];

// SQL language configuration for Monaco Editor
export const SQL_LANGUAGE_CONFIGURATION: Monaco.languages.IMonarchLanguage = {
  defaultToken: '',
  tokenPostfix: '.sql',
  ignoreCase: true,

  brackets: [
    {open: '[', close: ']', token: 'delimiter.square'},
    {open: '(', close: ')', token: 'delimiter.parenthesis'},
  ],

  keywords: DUCKDB_KEYWORDS,
  operators: SQL_OPERATORS,
  builtinFunctions: DUCKDB_FUNCTIONS,
  builtinVariables: SQL_VARIABLES,
  pseudoColumns: SQL_PSEUDO_COLUMNS,

  tokenizer: {
    root: [
      {include: '@comments'},
      {include: '@whitespace'},
      {include: '@numbers'},
      {include: '@strings'},
      {include: '@complexIdentifiers'},
      {include: '@scopes'},
      [/[;,.]/, 'delimiter'],
      [/[()]/, '@brackets'],
      [
        /[\w@#$]+/,
        {
          cases: {
            '@keywords': 'keyword',
            '@operators': 'operator',
            '@builtinFunctions': 'predefined',
            '@builtinVariables': 'predefined',
            '@pseudoColumns': 'predefined',
            '@default': 'identifier',
          },
        },
      ],
      [/[<>=!%&+\-*/|~^]/, 'operator'],
    ],
    whitespace: [[/\s+/, 'white']],
    comments: [
      [/--+.*/, 'comment'],
      [/\/\*/, {token: 'comment.quote', next: '@comment'}],
    ],
    comment: [
      [/[^*/]+/, 'comment'],
      [/\*\//, {token: 'comment.quote', next: '@pop'}],
      [/./, 'comment'],
    ],
    numbers: [
      [/0[xX][0-9a-fA-F]*/, 'number'],
      [/[$][+-]*\d*(\.\d*)?/, 'number'],
      [/((\d+(\.\d*)?)|(\.\d+))([eE][-+]?\d+)?/, 'number'],
    ],
    strings: [
      [/'/, {token: 'string', next: '@string'}],
      [/"/, {token: 'string.double', next: '@stringDouble'}],
    ],
    string: [
      [/[^']+/, 'string'],
      [/''/, 'string'],
      [/'/, {token: 'string', next: '@pop'}],
    ],
    stringDouble: [
      [/[^"]+/, 'string.double'],
      [/""/, 'string.double'],
      [/"/, {token: 'string.double', next: '@pop'}],
    ],
    complexIdentifiers: [
      [/\[/, {token: 'identifier.quote', next: '@bracketedIdentifier'}],
      [/"/, {token: 'identifier.quote', next: '@quotedIdentifier'}],
    ],
    bracketedIdentifier: [
      [/[^\]]+/, 'identifier'],
      [/]]/, 'identifier'],
      [/]/, {token: 'identifier.quote', next: '@pop'}],
    ],
    quotedIdentifier: [
      [/[^"]+/, 'identifier'],
      [/""/, 'identifier'],
      [/"/, {token: 'identifier.quote', next: '@pop'}],
    ],
    scopes: [],
  },
} as const satisfies Monaco.languages.IMonarchLanguage;
