/**
 * {@include ../README.md}
 * @packageDocumentation
 */

export {
  createAppClient,
  installGlobalClient,
  AppRuntimeError,
  type AppRuntimeClient,
  type CreateAppClientOptions,
} from './client';
export {
  createDiagnosticPreludeScript,
  createBridgeHost,
  type AppRuntimeHost,
  type AppRuntimeHostHandlers,
  type CreateDiagnosticPreludeScriptOptions,
  type CreateBridgeHostOptions,
} from './host';
export {
  APP_RUNTIME_MESSAGE_TYPE,
  APP_RUNTIME_PROTOCOL_VERSION,
  AppCapability,
  AppDiagnostic,
  AppDiagnosticLevel,
  AppDiagnosticSource,
  QueryColumn,
  QueryRequest,
  QueryResult,
  RuntimeDiagnosticMessage,
  RuntimeErrorCode,
  RuntimeErrorPayload,
  RuntimeMessage,
  RuntimeRequestMessage,
  RuntimeRequestMethod,
  RuntimeResponseMessage,
  createRuntimeDiagnostic,
  createRuntimeErrorResponse,
  createRuntimeRequest,
  createRuntimeResponse,
  type AppCapability as AppCapabilityType,
  type AppDiagnostic as AppDiagnosticType,
  type AppDiagnosticLevel as AppDiagnosticLevelType,
  type AppDiagnosticSource as AppDiagnosticSourceType,
  type QueryColumn as QueryColumnType,
  type QueryRequest as QueryRequestType,
  type QueryResult as QueryResultType,
  type RuntimeDiagnosticMessage as RuntimeDiagnosticMessageType,
  type RuntimeErrorCode as RuntimeErrorCodeType,
  type RuntimeErrorPayload as RuntimeErrorPayloadType,
  type RuntimeMessage as RuntimeMessageType,
  type RuntimeRequestMessage as RuntimeRequestMessageType,
  type RuntimeRequestMethod as RuntimeRequestMethodType,
  type RuntimeResponseMessage as RuntimeResponseMessageType,
} from './protocol';
export {
  HTML_APP_REDO_REVISION_COMMAND_ID,
  HTML_APP_RENAME_COMMAND_ID,
  HTML_APP_RESTORE_REVISION_COMMAND_ID,
  HTML_APP_REVISION_COMMAND_IDS,
  HTML_APP_UNDO_REVISION_COMMAND_ID,
  HTML_APP_WRITE_REVISION_COMMAND_ID,
  createHtmlAppRevisionCommands,
  type CreateHtmlAppRevisionCommandsOptions,
} from './HtmlAppRevisionCommands';
export {
  createHtmlAppBlockDocumentBlock,
  type CreateHtmlAppBlockDocumentBlockOptions,
  type HtmlAppBlockDocumentBlock,
} from './html-app-block-document';
export {
  HTML_APP_BLOCK_TYPE,
  HtmlAppBlock,
  HtmlAppDependency,
  HtmlAppRevision,
  HtmlAppRevisionSource,
  HtmlAppRuntimeConfig,
  HtmlAppSourceFileMap,
  HtmlAppState,
  commitHtmlAppRevisionState,
  createDefaultHtmlAppFiles,
  createHtmlAppBlockDefinition,
  createHtmlAppRuntimeSlice,
  createHtmlAppSrcDoc,
  executeReadonlyQuery,
  getCurrentHtmlAppRevision,
  getHtmlAppRevisionList,
  getHtmlAppRevisionNavigationState,
  redoHtmlAppRevisionState,
  restoreHtmlAppRevisionState,
  resolveHtmlAppDependencyUrl,
  undoHtmlAppRevisionState,
  type CommitHtmlAppRevisionMetadata,
  type CreateHtmlAppBlockDefinitionOptions,
  type CreateHtmlAppRuntimeSliceOptions,
  type HtmlAppBlockProps,
  type HtmlAppDependency as HtmlAppDependencyType,
  type HtmlAppRevision as HtmlAppRevisionType,
  type HtmlAppRevisionNavigationState,
  type HtmlAppRevisionPatch,
  type HtmlAppRevisionSource as HtmlAppRevisionSourceType,
  type HtmlAppRuntimeConfig as HtmlAppRuntimeConfigType,
  type HtmlAppRuntimeQueryState,
  type HtmlAppRuntimeSliceState,
  type HtmlAppSourceFileMap as HtmlAppSourceFileMapType,
  type HtmlAppState as HtmlAppStateType,
  type RestoreHtmlAppRevisionMetadata,
} from './html-app';
