/**
 * Build-time script that walks skills/<id>/, reads SKILL.md (+ any other *.md
 * files as extras), validates each manifest via loadSkillFromFiles from
 * @sqlrooms/ai, and emits src/skills/bundledSkills.ts exporting
 * BUNDLED_SKILLS: SkillRecord[].
 *
 * Run: npx tsx scripts/generate-skills.ts
 */
import {createRequire} from 'module';
import {readdirSync, readFileSync, writeFileSync, statSync, existsSync, mkdirSync} from 'fs';
import {dirname, join, relative} from 'path';
import {pathToFileURL} from 'url';
import type {SkillFile, SkillRecord} from '@sqlrooms/ai';

const BUILT_IN_ROOT_ID = 'built-in';

const require = createRequire(import.meta.url);
const sqlroomsAiDir = dirname(dirname(require.resolve('@sqlrooms/ai')));
const skillsEntry = join(sqlroomsAiDir, 'dist', 'skills', 'index.js');
const {loadSkillFromFiles} = (await import(pathToFileURL(skillsEntry).href)) as {
  loadSkillFromFiles: (files: SkillFile[]) => Omit<SkillRecord, 'ref'>;
};

const SKILLS_DIR = join(import.meta.dirname, '..', 'skills');
const OUTPUT_DIR = join(import.meta.dirname, '..', 'src', 'skills');
const OUTPUT_FILE = join(OUTPUT_DIR, 'bundledSkills.ts');

function collectSkillFiles(skillDir: string): SkillFile[] {
  const out: SkillFile[] = [];
  function walk(dir: string) {
    for (const entry of readdirSync(dir, {withFileTypes: true})) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
        continue;
      }
      const relativePath = relative(skillDir, fullPath);
      if (relativePath === 'skill.yaml' || relativePath === 'SKILL.md' || entry.name.endsWith('.md')) {
        out.push({relativePath, content: readFileSync(fullPath, 'utf-8')});
      }
    }
  }
  walk(skillDir);
  return out;
}

function loadOneSkill(skillDir: string, dirName: string): SkillRecord {
  const files = collectSkillFiles(skillDir);
  let loaded;
  try {
    loaded = loadSkillFromFiles(files);
  } catch (err) {
    throw new Error(`Failed to load skill in ${dirName}: ${err instanceof Error ? err.message : String(err)}`);
  }
  return {
    ref: {rootId: BUILT_IN_ROOT_ID, id: loaded.manifest.id},
    ...loaded,
  };
}

function generate(): void {
  const skillDirs = readdirSync(SKILLS_DIR, {withFileTypes: true})
    .filter((d) => d.isDirectory())
    .filter(
      (d) =>
        existsSync(join(SKILLS_DIR, d.name, 'SKILL.md')) && statSync(join(SKILLS_DIR, d.name, 'SKILL.md')).isFile(),
    );

  const skills: SkillRecord[] = skillDirs
    .map((d) => loadOneSkill(join(SKILLS_DIR, d.name), d.name))
    .sort((a, b) => a.manifest.id.localeCompare(b.manifest.id));

  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, {recursive: true});
  }

  const output = `// Auto-generated by scripts/generate-skills.ts — DO NOT EDIT
import type {SkillRecord} from '@sqlrooms/ai';

export const BUNDLED_SKILLS: SkillRecord[] = ${JSON.stringify(skills)};
`;

  writeFileSync(OUTPUT_FILE, output, 'utf-8');
  const totalExtras = skills.reduce((n, s) => n + s.extraFiles.length, 0);
  console.log(`Generated ${OUTPUT_FILE} with ${skills.length} skills (${totalExtras} extra files)`);
}

generate();
