import {Selection} from '@uwdata/mosaic-core';
import {sql} from '@uwdata/mosaic-sql';
import type {DuckDbSliceState} from '@sqlrooms/duckdb';
import {inspectLocalSelect, needsLocalReadApproval} from '@sqlrooms/mcp/room';

/** Portable predicates generated by Mosaic; runtime clients are never serialized. */
export function selectionPredicates(selection: Selection): string[] {
  return selection.clauses.flatMap((clause) =>
    clause.predicate ? [String(clause.predicate)] : [],
  );
}

/** Restore saved filters as a visible baseline, removable with the explorer's Reset. */
export function restoreSelection(selection: Selection, predicates: string[]) {
  selection.reset();
  for (const predicate of predicates)
    selection.update({source: {}, value: true, predicate: sql`${predicate}`});
}

/** Reject filters that could read external sources or perform unverified SQL. */
export async function validateTableFilters(
  db: DuckDbSliceState['db'],
  predicates: string[],
) {
  for (const predicate of predicates) {
    const statements = await inspectLocalSelect(
      db,
      `SELECT 1 WHERE (${predicate})`,
      '__roomie',
    );
    if (await needsLocalReadApproval(db, statements))
      throw new Error(
        'Table filters must use ordinary local expressions. External or unverified SQL is not supported.',
      );
  }
}

/** Observe user filters while suppressing intermediate events from saved-state restoration. */
export function synchronizeTableSelection(
  selection: Selection,
  onChange: (predicates: string[]) => void,
) {
  let restoring: string[] | undefined;
  const equal = (first: string[], second: string[]) =>
    JSON.stringify(first) === JSON.stringify(second);
  const receive = () => {
    const predicates = selectionPredicates(selection);
    if (restoring) {
      if (equal(predicates, restoring)) restoring = undefined;
      return;
    }
    onChange(predicates);
  };
  selection.addEventListener('value', receive);
  return {
    restore: (predicates: string[]) => {
      if (!restoring && equal(selectionPredicates(selection), predicates))
        return;
      restoring = [...predicates];
      restoreSelection(selection, predicates);
      // Resetting an already-empty selection can cancel queued changes without
      // emitting a final event. Nonempty restorations finish in receive().
      if (!predicates.length && !selectionPredicates(selection).length)
        restoring = undefined;
    },
    dispose: () => selection.removeEventListener('value', receive),
  };
}
